export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export const API_ENDPOINTS = {
    DATASETS: {
        LIST: `${API_BASE_URL}/api/annotations/datasets/list`,
        SUMMARY: `${API_BASE_URL}/api/annotations/datasets/summary`,
        CREATE: `${API_BASE_URL}/api/annotations/datasets/create`,
        GET: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}`,
        DELETE: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}`,
        STATS: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}/stats`,
        UPLOAD: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}/upload`,
        EXPORT: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}/export`,
        EXPORT_STATUS: (id, jobId) => `${API_BASE_URL}/api/annotations/datasets/${id}/export-status/${jobId}`,
        ANALYZE: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}/analyze`,
        QUALITY_HISTORY: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}/quality-history`,
        DOWNLOAD_FORMAT: (id, format) => `${API_BASE_URL}/api/annotations/datasets/${id}/download-format?format=${format}`,
        UPLOAD_VIDEO: (id) => `${API_BASE_URL}/api/annotations/datasets/${id}/upload-video`,
        MEMBERS: (id) => `${API_BASE_URL}/api/datasets/${id}/members`,
        MEMBER_REMOVE: (id, userId) => `${API_BASE_URL}/api/datasets/${id}/members/${userId}`,
        ACTIVITY: (id) => `${API_BASE_URL}/api/datasets/${id}/activity`,
        ACCEPT_INVITE: `${API_BASE_URL}/api/datasets/invites/accept`,
    },
    ANNOTATIONS: {
        GET_IMAGE: (datasetId, filename, token) => `${API_BASE_URL}/api/annotations/image/${datasetId}/${filename}${token ? `?token=${token}` : ''}`,
        GET_ANNOTATION: (datasetId, imageId) => `${API_BASE_URL}/api/annotations/annotations/${datasetId}/${imageId}`,
        SAVE: `${API_BASE_URL}/api/annotations/save`,
        AUTO_LABEL: `${API_BASE_URL}/api/annotations/auto-label`,
        AUTO_LABEL_STATUS: (datasetId, jobId) => `${API_BASE_URL}/api/annotations/datasets/${datasetId}/auto-label-status/${jobId}`,
        UNCERTAINTY: (datasetId) => `${API_BASE_URL}/api/annotations/datasets/${datasetId}/uncertainty`,
        EXPORT_STATUS: (datasetId, jobId) => `${API_BASE_URL}/api/annotations/datasets/${datasetId}/export-status/${jobId}`,
        DOWNLOAD: (datasetId) => `${API_BASE_URL}/api/annotations/datasets/${datasetId}/download`,
    },
    TRAINING: {
        START: `${API_BASE_URL}/api/training/start`,
        START_FROM_DATASET: `${API_BASE_URL}/api/training/start-from-dataset`,
        START_MICRO: `${API_BASE_URL}/api/training/start-micro`,
        EXPORT_AND_TRAIN: `${API_BASE_URL}/api/training/export-and-train`,
        VERSIONS_GENERATE: `${API_BASE_URL}/api/training/versions/generate`,
        VERSIONS_LIST: (id) => `${API_BASE_URL}/api/training/versions/list/${id}`,
        QUEUE_STATUS: `${API_BASE_URL}/api/training/queue-status`,
        JOBS: `${API_BASE_URL}/api/training/jobs`,
        STATUS: (id) => `${API_BASE_URL}/api/training/status/${id}`,
        JOB: (id) => `${API_BASE_URL}/api/training/job/${id}`,
        CANCEL: (id) => `${API_BASE_URL}/api/training/cancel/${id}`,
        JOB_METRICS: (id) => `${API_BASE_URL}/api/training/job/${id}/metrics`,
        TERMINATE: (id) => `${API_BASE_URL}/api/training/job/${id}`,
        PREVIEW_AUGMENTATION: `${API_BASE_URL}/api/training/preview-augmentation`,
        PREFLIGHT: (datasetId) => `${API_BASE_URL}/api/training/preflight/${datasetId}`,
        CONFUSION_MATRIX: (jobId) => `${API_BASE_URL}/api/training/job/${jobId}/confusion-matrix`,
        PER_CLASS_METRICS: (jobId) => `${API_BASE_URL}/api/training/job/${jobId}/per-class-metrics`,
        PRESETS: `${API_BASE_URL}/api/training/presets`,
        AUTO_RETRAIN_CONFIG: `${API_BASE_URL}/api/training/auto-retrain-config`,
        AUTO_RETRAIN_CONFIG_GET: (datasetId) => `${API_BASE_URL}/api/training/auto-retrain-config/${datasetId}`,
    },
    SMART: {
        SEGMENT: `${API_BASE_URL}/api/smart/segment`,
    },
    MODELS: {
        LIST: `${API_BASE_URL}/api/models/list`,
        DELETE: (name) => `${API_BASE_URL}/api/models/delete/${name}`,
        DOWNLOAD: (name) => `${API_BASE_URL}/api/models/download/${name}`,
        EXPORT: (name, format) => `${API_BASE_URL}/api/models/export/${name}?format=${format}`,
        INFO: (name) => `${API_BASE_URL}/api/models/info/${name}`,
    },
    INFERENCE: {
        PREDICT: `${API_BASE_URL}/api/inference/predict`,
        PREDICT_BATCH: `${API_BASE_URL}/api/inference/predict-batch`,
        LIST: `${API_BASE_URL}/api/inference/models`,
    },
    AUTH: {
        ME: `${API_BASE_URL}/api/auth/me`,
        UPDATE_PROFILE: `${API_BASE_URL}/api/auth/me`,
        STATS: `${API_BASE_URL}/api/auth/me/stats`,
    },
    HEALTH: `${API_BASE_URL}/health`,
    VIDEO: {
        EXTRACT_FRAMES: `${API_BASE_URL}/api/video/extract-frames`,
    },
    ACTIVE_LEARNING: {
        COLLECT: `${API_BASE_URL}/api/active-learning/collect`,
        COLLECT_STATUS: (datasetId) => `${API_BASE_URL}/api/active-learning/collect-status/${datasetId}`,
        UNCERTAIN: (datasetId) => `${API_BASE_URL}/api/active-learning/uncertain/${datasetId}`,
        APPROVE: `${API_BASE_URL}/api/active-learning/approve`,
        REJECT: `${API_BASE_URL}/api/active-learning/reject`,
    },
    MONITORING: {
        LOG: `${API_BASE_URL}/api/monitoring/log`,
        STATS: (datasetId) => `${API_BASE_URL}/api/monitoring/stats/${datasetId}`,
        DRIFT: (datasetId) => `${API_BASE_URL}/api/monitoring/drift/${datasetId}`,
    },
};
